apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData: 
  production.yaml: |
    kafka:
      broker:
      - pkc-419q3.us-east4.gcp.confluent.cloud:9092
      sasl:
        username: 7RUKK6IDRAEHFOTX
        password: cfltEY1QNdDerfuIk0j1HAxfSKsDCUa+G2BeamZxRbEMhAJvAfoyeCaBTN1ftTsw
    mail:
      host: smtp.ethereal.email
      port: 587
      auth:
        user: kaitlyn98@ethereal.email
        password: uE9WbHkw1npE5T9w8X
      from: '"Vedant_Jathar" <vedant@gmail.com>'
    clientUI:
      url: http://localhost:3000


